import pandas as pd 

encoding_mapping = {
    8000: "Unspecified carcinoma",
    8001: "Unspecified carcinoma",
    8002: "small cell carcinoma",
    8004: "other specified carcinoma",
    8005: "other specified carcinoma",
    8010: "Unspecified carcinoma",
    8012: "large cell carcinoma",
    8013: "large cell carcinoma",
    8014: "large cell carcinoma",
    8020: "Unspecified carcinoma",
    8021: "large cell carcinoma",
    8022: "other specified carcinoma",
    8030: "other specified carcinoma",
    8031: "other specified carcinoma",
    8032: "other specified carcinoma",
    8033: "other specified carcinoma",
    8034: "large cell carcinoma",
    8041: "small cell carcinoma",
    8042: "small cell carcinoma",
    8043: "small cell carcinoma",
    8044: "small cell carcinoma",
    8045: "small cell carcinoma",
    8046: "Unspecified carcinoma",
    8050: "adenocarcinoma",
    8052: "squamous cell carcinoma",
    8070: "squamous cell carcinoma",
    8071: "squamous cell carcinoma",
    8072: "squamous cell carcinoma",
    8073: "squamous cell carcinoma",
    8074: "squamous cell carcinoma",
    8075: "squamous cell carcinoma",
    8082: "large cell carcinoma",
    8083: "squamous cell carcinoma",
    8084: "squamous cell carcinoma",
    8123: "squamous cell carcinoma",
    8140: "adenocarcinoma",
    8141: "adenocarcinoma",
    8144: "adenocarcinoma",
    8200: "other specified carcinoma",
    8201: "adenocarcinoma",
    8211: "adenocarcinoma",
    8230: "Unspecified carcinoma",
    8240: "other specified carcinoma",
    8243: "other specified carcinoma",
    8244: "other specified carcinoma",
    8245: "other specified carcinoma",
    8246: "other specified carcinoma",
    8247: "other specified carcinoma",
    8249: "other specified carcinoma",
    8250: "adenocarcinoma",
    8251: "adenocarcinoma",
    8252: "adenocarcinoma",
    8253: "adenocarcinoma",
    8254: "adenocarcinoma",
    8255: "adenocarcinoma",
    8256: "adenocarcinoma",
    8257: "adenocarcinoma",
    8260: "adenocarcinoma",
    8265: "adenocarcinoma",
    8290: "adenocarcinoma",
    8310: "adenocarcinoma",
    8323: "adenocarcinoma",
    8333: "adenocarcinoma",
    8341: "Non-lung cancer",
    8401: "adenocarcinoma",
    8430: "other specified carcinoma",
    8441: "Non-lung cancer",
    8470: "adenocarcinoma",
    8480: "adenocarcinoma",
    8481: "adenocarcinoma",
    8490: "adenocarcinoma",
    8500: "adenocarcinoma",
    8507: "adenocarcinoma",
    8524: "adenocarcinoma",
    8550: "adenocarcinoma",
    8551: "adenocarcinoma",
    8560: "other specified carcinoma",
    8562: "other specified carcinoma",
    8570: "adenocarcinoma",
    8571: "adenocarcinoma",
    8574: "adenocarcinoma",
    8575: "other specified carcinoma",
    8576: "adenocarcinoma",
    8580: "Non-lung cancer",
    8693: "Sarcomas and soft tissue tumors",
    8720: "Non-lung cancer",
    8800: "Sarcomas and soft tissue tumors",
    8801: "Sarcomas and soft tissue tumors",
    8802: "Sarcomas and soft tissue tumors",
    8803: "Sarcomas and soft tissue tumors",
    8804: "Sarcomas and soft tissue tumors",
    8805: "Sarcomas and soft tissue tumors",
    8810: "Sarcomas and soft tissue tumors",
    8811: "Sarcomas and soft tissue tumors",
    8815: "Sarcomas and soft tissue tumors",
    8830: "Sarcomas and soft tissue tumors",
    8854: "Sarcomas and soft tissue tumors",
    8890: "Sarcomas and soft tissue tumors",
    8891: "Sarcomas and soft tissue tumors",
    8900: "Sarcomas and soft tissue tumors",
    8920: "Sarcomas and soft tissue tumors",
    8933: "Sarcomas and soft tissue tumors",
    8940: "Unspecified carcinoma",
    8972: "Unspecified carcinoma",
    8980: "other specified carcinoma",
    8982: "Unspecified carcinoma",
    8990: "Sarcomas and soft tissue tumors",
    9040: "Sarcomas and soft tissue tumors",
    9041: "Sarcomas and soft tissue tumors",
    9043: "Sarcomas and soft tissue tumors",
    9064: "Non-lung cancer",
    9100: "Non-lung cancer",
    9101: "Non-lung cancer",
    9120: "Sarcomas and soft tissue tumors",
    9133: "Sarcomas and soft tissue tumors",
    9180: "Sarcomas and soft tissue tumors",
    9181: "Sarcomas and soft tissue tumors",
    9220: "Sarcomas and soft tissue tumors",
    9231: "Sarcomas and soft tissue tumors",
    9260: "Unspecified carcinoma",
    9364: "Non-lung cancer",
    9540: "Sarcomas and soft tissue tumors"
}

# Load datasets
df_taiwan = pd.read_csv('Data_folder/Taiwan_en.csv')
df_usa = pd.read_csv('Data_folder/SEER_en.csv')

# Define mapping (assuming encoding_mapping is already defined)
df_taiwan['PTHLTYPE_Histology'] = df_taiwan['PTHLTYPE'].map(encoding_mapping)
df_usa['PTHLTYPE_Histology'] = df_usa['PTHLTYPE'].map(encoding_mapping)

# Save df_taiwan to a CSV file
df_taiwan.to_csv('Data_folder/Taiwan_en_modified.csv', index=False)
df_usa.to_csv('Data_folder/SEER_en_modified.csv', index=False)

